import { makeVar } from "@apollo/client";
import { CustomJwtPayload } from "../libs/types/customJwtPayload";


export const themeVar = makeVar({});
export const userVar = makeVar<CustomJwtPayload>({
	_id: '',
	type: '',
	status: '',
	authType: '',
	titleNick: '',
	// password: '',
	fullName: '',
	image: '',
	viewImage: '',
	address: '',
	shortDesc: '',
	longDesc: '',
	phone: '',
	phone2: '',
	email: '',
	kakaoTalk: '',
	youtube: '',
	instagram: '',
	facebook: '',
	tikTok: '',
	naverBlog: '',
	xcom: '',
	followers: 0,
	followings: 0,
	likes: 0,
	views: 0,
	comments: 0,
	warnings: 0,
	articles: 0,
	blocks: 0,
	memberCars: 0,
	usedCars: 0,
	newCars: 0,
	rank: 0,
	points: 0,
	sellerProducts: 0,
	dealerFinancing: false,
	dealerCarService: false,
	dealerTradeIn: false,
	dealerCustomization: false,
	dealerWarranties: false,
	dealerParts: false,
	dealerAccessories: false,
	dealerCarDetailing: false,
	dealerCarWash: false,
	dealerCarTestDrive: false,
	dealerCarDelivery: false,
	carOilChange: false,
	carAlignment: false,
	carTireChange: false,
	carBrakeCheck: false,
	carBatteryCheck: false,
	carTireBalance: false,
	carSuspension: false,
	carAirCondition: false,
	carTransmissionCheck: false,
	carEngineDiagnostic: false,
	carExhaust: false,
	carDetailing: false,
	carWindshield: false,
	carTimingBelt: false,
	carChainReplacement: false,
	comfort: 0,
	performance: 0,
	exterior: 0,
	interior: 0,
	reliability: 0,
	fast: 0,
	openAt: '',
	closeAt: '',
	openSunday: '',
	closeSunday: '',
	openSaturday: '',
	closeSaturday: '',
	publicHolidays: false,
});

// @ts-ignore
export const socketVar = makeVar<WebSocket>()
