services: 
  carselon-client: 
    container_name: carselon-client
    restart: always
    image: node:20.18.1
    ports: 
      - 1000:1000
    environment: 
      - PORT=1000

    volumes: 
      - ./:/user/src/carselon-client
    working_dir: /user/src/carselon-client

    networks: 
      - client-network
    
    command: bash -c "yarn && yarn run build && yarn run start"


networks: 
  client-network:
    driver: bridge
