export enum Type {
	USER = 'USER',
	AGENT = 'AGENT',
	ADMIN = 'ADMIN',
	DEALER = 'DEALER',
	SERVICE = 'SERVICE',
	SELLER = 'SELLER',
}

export enum Status {
	ACTIVE = 'ACTIVE',
	BLOCK = 'BLOCK',
	DELETE = 'DELETE',
}

export enum AuthType {
	PHONE = 'PHONE',
	EMAIL = 'EMAIL',
	KAKAOTALK = 'KAKAOTALK',
	TELEGRAM = 'TELEGRAM',
}

export enum Brand {
	HYUNDAI = 'Hyundai',
	KIA = 'KIA',
	GENESIS = 'Genesis',
	SSANGYONG = 'SsangYong',
	TESLA = 'Tesla',
	TOYOTA = 'Toyota',
	BYD = 'BYD',
	ROLLS_ROYCE = 'Rolls-Royce',
	BENTLEY = 'Bentley',
	ASTON_MARTIN = 'Aston Martin',
	JAGUAR = 'Jaguar',
	LAND_ROVER = 'Land Rover',
	BMW = 'BMW',
	MERCEDES_BENZ = 'Mercedes-Benz',
	AUDI = 'Audi',
	PORSCHE = 'Porsche',
	MASERATI = 'Maserati',
	LEXUS = 'Lexus',
	CADILLAC = 'Cadillac',
	LINCOLN = 'Lincoln',
	ALFA_ROMEO = 'Alfa Romeo',
	VOLVO = 'Volvo',
	PAGANI = 'Pagani',
	KOENIGSEGG = 'Koenigsegg',
	MCLAREN = 'McLaren',
	FERRARI = 'Ferrari',
	LAMBORGHINI = 'Lamborghini',
	CHEVROLET = 'Chevrolet',
	NISSAN = 'Nissan',
	FORD_MUSTANG = 'Ford Mustang',
	CATERHAM = 'Caterham',
	SPYKER = 'Spyker',
	ZAGATO = 'Zagato',
	GARDON_MURRAY = 'Gordon Murray',
	LOTUS = 'Lotus',
	DODGE_VIPER = 'Dodge Viper',
	BUGATTI = 'Bugatti',
	FORD_GT = 'Ford GT',
	ZENVO = 'Zenvo',
	SSC_TUATARA = 'SSC Tuatara',
	RIMAC = 'Rimac',
	NOBLE = 'Noble',
	NIO = 'NIO',
	XPENG = 'XPeng',
	RIVIAN = 'Rivian',
	LUCID = 'Lucid',
	POLESTAR = 'Polestar',
	FISKER = 'Fisker',
	BOLLINGER = 'Bollinger',
	FARADAY_FUTURE = 'Faraday Future',
	HONDA = 'Honda',
	FORD = 'Ford',
	PEUGEOT = 'Peugeot',
	RENAULT = 'Renault',
	MINI = 'MINI',
	FIAT = 'FIAT',
	SUZUKI = 'Suzuki',
	CITROEN = 'Citroën',
	MAZDA = 'Mazda',
	SKODA = 'Škoda',
	SEAT = 'SEAT',
	TATA = 'Tata',
	RANGE_ROVER = 'Range Rover',
	JEEP = 'Jeep',
	BUICK_LACROSSE = 'Buick LaCrosse',
	RAM = 'RAM',
	GMC = 'GMC',
	ISUZU = 'Isuzu',
	VOLKSWAGEN = 'Volkswagen',
	MITSUBISHI = 'Mitsubishi',
	SUBARU = 'Subaru',
	ACURA = 'Acura',
	INFINITI = 'Infiniti',
	CHERY = 'Chery',
	HUMMER = 'Hummer',
	OPEL = 'Opel',
	ZEEKR = 'Zeekr',
	OTHER = 'Other',
}

export enum Location {
	SEOUL = 'Seoul',
	BUSAN = 'Busan',
	INCHEON = 'Incheon',
	DAEGU = 'Daegu',
	DAEJEON = 'Daejeon',
	GWANGJU = 'Gwangju',
	ULSAN = 'Ulsan',
	SUWON = 'Suwon',
	GYEONGJU = 'Gyeongju',
	JEONJU = 'Jeonju',
	JEJU = 'Jeju',
	CHANGWON = 'Changwon',
	POHANG = 'Pohang',
	CHEONAN = 'Cheonan',
	GIMHAE = 'Gimhae',
	CHEONGJU = 'Cheongju',
	WONJU = 'Wonju',
	IKSAN = 'Iksan',
	MOKPO = 'Mokpo',
	ANDONG = 'Andong',
	ASAN = 'Asan',
	ANSAN = 'Ansan',
	PYEONGTAEK = 'Pyeongtaek',
	YANGSAN = 'Yangsan',
	JEONGEUP = 'Jeonggeup',
	GIMPO = 'Gimpo',
	GUNSAN = 'Gunsan',
	GIMCHEON = 'Gimcheon',
	GANGNEUNG = 'Gangeung',
	UIJEONGBU = 'Uijeongbu',
	ICHEON = 'Icheon',
	PAJU = 'Paju',
	TONGYEONG = 'Tongyeong',
	CHUNCHEON = 'Chuncheon',
	SOKCHO = 'Sokcho',
	NAJU = 'Naju',
	GYEONGSAN = 'Gyeongsan',
	HWASEONG = 'Hwaseong',
	YEOJU = 'Yeoju',
	SEONGNAM = 'Seongnam',
	OTHER = 'Other',
}

export enum CarServiceType {
	OIL_CHANGE = 'Oil Change',
	BATTERY = 'Battery',
	TIRE = 'Tire',
	BRAKE = 'Brake',
	ENGINE = 'Engine',
	SYSTEM = 'System',
	WINDSHIELD = 'Windshield',
	AIR_CONDITION = 'Air Condition',
	BODY_CRASH = 'Body Crash',
	TUNING = 'Tuning',
	OTHER = 'Other',
}
